name: sankey_ai
description: "Sankey AI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sankey_flutter: ^0.0.1
  screenshot: ^3.0.0
  path_provider: ^2.1.2
  firebase_core: ^3.13.0
  cloud_functions: ^5.5.0
  firebase_app_check: ^0.3.2+5
  dart_mappable: ^4.5.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  fpdart: ^1.1.1
  auto_route: ^10.0.1
  flutter_bloc: ^9.1.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr: ^2.3.1
  dart_mappable_builder: ^4.5.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    
  flavors:
    dev:
      app:
        name: "Sankey Ai Dev"
      android:
        applicationId: "com.caiobueno.sankey_ai.dev"
      ios:
        bundleId: "com.caiobueno.sankeyAi.dev"
    
    stg:
      app:
        name: "Sankey Ai Stg"
      android:
        applicationId: "com.caiobueno.sankey_ai.stg"  
      ios:
        bundleId: "com.caiobueno.sankeyAi.stg"
    
    prod:
      app:
        name: "Sankey Ai"
      android:
        applicationId: "com.caiobueno.sankey_ai"  
      ios:
        bundleId: "com.caiobueno.sankeyAi"
